/*
 * Author: Dan Niyazov 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cc;

/**
 *
 * @author danniyazov
 */
public enum CodeCheckProp {
    PREV_BUTTON_TEXT,
    NEXT_BUTTON_TEXT,
    HOME_BUTTON_TEXT,
    NEW_BUTTON_TEXT,
    LOAD_BUTTON_TEXT,
    RENAME_BUTTON_TEXT,
    ABOUT_BUTTON_TEXT,
    REMOVE_BUTTON_TOOLTIP,
    VIEW_BUTTON_TOOLTIP,
    REFRESH_BUTTON_TOOLTIP,
    UNZIP_BUTTON_TEXT,
    EXTRACT_BUTTON_TEXT,
    EXTRACT_CODE_BUTTON_TEXT,
    CHECK_CODE_BUTTON_TEXT,
    RESULTS_BUTTON_TEXT,
    STEP_ONE_LIST_TITLE,
    STEP_TWO_LIST_TITLE,
    STEP_THREE_LIST_TITLE,
    STEP_FOUR_LIST_TITLE,
    STEP_FIVE_LIST_TITLE,
    FILE_TYPE_LABEL,
    FILE_TYPE_CUSTOM,
    
    PREV_BUTTON_ICON,
    NEXT_BUTTON_ICON,
    HOME_BUTTON_ICON,
    RENAME_BUTTON_ICON,
    REFRESH_BUTTON_ICON,
    VIEW_BUTTON_ICON,
    ABOUT_BUTTON_ICON,
    REMOVE_BUTTON_ICON,
    UNZIP_BUTTON_ICON,
    EXTRACT_CODE_BUTTON_ICON,
    CHECK_CODE_BUTTON_ICON,
    RESULTS_BUTTON_ICON,
    
    APP_PATH_WORK,
    APP_TM_TEXT,
    APP_VERSION,
    APP_PERSISTENT_DATA,
    
    WELCOME_TO_TEXT,
    WELCOME_VIEW_RECENTS_HEADER_TEXT,
    WELCOME_VIEW_NEW_BUTTON_TEXT,
    
    NEW_DIALOG_TITLE_TEXT,
    NEW_DIALOG_PROMPT_TEXT,
    NEW_DIALOG_HEADER_TEXT,
    NEW_DIALOG_CONTENT_TEXT,
    NEW_DIALOG_ERROR_TEXT,
    NEW_DIALOG_EMPTY_TEXT,
    
    QUIT_DIALOG_TITLE_TEXT,
    QUIT_DIALOG_HEADER_TEXT,
    QUIT_DIALOG_CONTENT_TEXT,

    RENAME_DIALOG_TITLE_TEXT,
    RENAME_DIALOG_PROMPT_TEXT,
    RENAME_DIALOG_HEADER_TEXT,
    RENAME_DIALOG_CONTENT_TEXT,
    
    SUCCESS_EXTRACT_MESSAGE,
    FAIL_EXTRACT_MESSAGE,
    SUCCESS_RENAME_MESSAGE,
    FAIL_RENAME_MESSAGE,
    SUCCESS_UNZIP_MESSAGE,
    FAIL_UNZIP_MESSAGE,
    SUCCESS_CODE_EXTRACT_MESSAGE,
    FAIL_CODE_EXTRACT_MESSAGE,
    
    NO_SELECTION_TITLE,
    NO_SELECTION_MESSAGE,
    
    CORRUPT_CHECK_HEADER,
    CORRUPT_CHECK_MESSAGE,
    
    DELETE_PROMPT_HEADER,
    DELETE_PROMPT_MESSAGE,
    
    ZIP_ERROR_TITLE,
    ZIP_ERROR_MESSAGE,

    ABOUT_LABEL_TEXT,
    VERSION_TEXT,
    LEGAL_NOTICE,
    AUTHOR_TEXT

}
