/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cc;

/**
 *
 * @author danniyazov
 */
public enum CodeCheckProp {
    PREV_BUTTON_TEXT,
    NEXT_BUTTON_TEXT,
    HOME_BUTTON_TEXT,
    NEW_BUTTON_TEXT,
    LOAD_BUTTON_TEXT,
    RENAME_BUTTON_TEXT,
    ABOUT_BUTTON_TEXT,
    REMOVE_BUTTON_TEXT,
    UNZIP_BUTTON_TEXT,
    EXTRACT_BUTTON_TEXT,
    EXTRACT_CODE_BUTTON_TEXT,
    CHECK_CODE_BUTTON_TEXT,
    RESULTS_BUTTON_TEXT,
    STEP_ONE_LIST_TITLE,
    STEP_TWO_LIST_TITLE,
    STEP_THREE_LIST_TITLE,
    STEP_FOUR_LIST_TITLE,
    STEP_FIVE_LIST_TITLE,
    FILE_TYPE_LABEL,
    FILE_TYPE_CUSTOM,
    
    PREV_BUTTON_ICON,
    NEXT_BUTTON_ICON,
    HOME_BUTTON_ICON,
    RENAME_BUTTON_ICON,
    ABOUT_BUTTON_ICON,
    REMOVE_BUTTON_ICON,
    UNZIP_BUTTON_ICON,
    EXTRACT_CODE_BUTTON_ICON,
    CHECK_CODE_BUTTON_ICON,
    RESULTS_BUTTON_ICON,
    
    APP_PATH_WORK,
    APP_TM_TEXT,
    APP_VERSION,
    APP_PERSISTENT_DATA,
    
    WELCOME_TO_TEXT,
    WELCOME_VIEW_RECENTS_HEADER_TEXT,
    WELCOME_VIEW_NEW_BUTTON_TEXT,
    NEW_DIALOG_TITLE_TEXT,
    NEW_DIALOG_PROMPT_TEXT,
    NEW_DIALOG_HEADER_TEXT,
    NEW_DIALOG_CONTENT_TEXT,
    NEW_DIALOG_ERROR_TEXT,
    NEW_DIALOG_EMPTY_TEXT,
    
    ABOUT_LABEL_TEXT,
    VERSION_TEXT,
    LEGAL_NOTICE,
    AUTHOR_TEXT

}
